### ISSUE TITLE
Hover Colour on Navigation

### ISSUE THREAD

**Issue by ghost** [ImanGhader/non-for-profit#42]
Do you think it's hard to read? The contrast between the coral and the teal isn't the best. Not a big issue but something to consider.

**Comment by ghost** [comment]
Also there's no closing icon for the navigation that shows when it's open.

**Comment by gagn0369** [comment]
I noticed the same thing, @spar0057. Should we tweak the coral colour in base.css? Any suggestions for a better shade we could use?

Also, the nav toggle button is a background image within a "label", not an icon... I couldn't figure out how to edit the code to change the button. And this was the only code for a side nav I found that I could mae work. But I feel like I've seen burger menu icons that don't change on other sites and it's still self explanatory.

**Comment by gagn0369** [comment]
I think a pinker shade for the coral might work well.

**Comment by ghost** [comment]
Yeah I agree,  let's use a lighter/pinker coral. I considered having the background of each link be coral and the text white on hover, but that might not look as good. The colours we have now are similar in intensity so the coral doesn't pop as much.

**Comment by ghost** [comment]
I talked to Shelley about the navigation icon as well and she said something similar. It's fine the way it is.

**Comment by gagn0369** [comment]
maybe instead we could change the shades of teal? make the light shade a bit lighter, and dark a bit darker? thoughts?

**Comment by trac0040** [comment]
Maybe the nav background could be the lightest shade of teal? I think the nav icon is fine as is as well

**Comment by ghost** [comment]
I agree with changing the shade of teal. Try it and see how it works.
